### ISSUE TITLE
quantité produit dans achat

### ISSUE THREAD

**Issue by ayoubensidhoum** [charaf113/OneRakTa3ref#116]
Une erreur dans calcules des quantités du produit

si je prend un produit je le sélectionne avec code-barre et je mets la quantité 10 avec un certain prix A

après je sélectionne le même produit avec une quantité de 90 avec un prix B

le prix total sera calculer A+B mais la quantité il prend que la dernière d'après les essais.

**Comment by charaf113** [comment]
réglé
