### ISSUE TITLE
ajout produit

### ISSUE THREAD

**Issue by ayoubensidhoum** [charaf113/OneRakTa3ref#120]
quand je remplis les champs et je génère le code barre quand j'imprime tout les champs devenu vide a voir svp

**Comment by charaf113** [comment]
je propose d'enlever le button imprimer puisque j'ai mis l'impression dans la liste des produits

**Comment by ayoubensidhoum** [comment]
faut la mettre alors sinon je propose que le bouton imprimer sera afficher après l'ajout et on reste sur le meme interface

**Comment by charaf113** [comment]
Pour cette version puisque on a pas assez de temps je préfère laisser l'impression dans la liste des produits et l'enlever sur la partie ajout
