### ISSUE TITLE
Interface vendeur 

### ISSUE THREAD

**Issue by ayoubensidhoum** [charaf113/OneRakTa3ref#124]
Déconnexion d'un Vendeur : remplacer Administrateur b Vendreur

**Comment by lotfiAliane** [comment]
c'est fait

**Comment by ayoubensidhoum** [comment]
Mazal pk tu me dis c'est fait alors que mazal et ma question et simple w bayna ne me dis pas j'ai pas compris : ki tji déconnecté f vendeur rah kayen administrateur alors que c un vendeur

**Comment by lotfiAliane** [comment]
c'est réglé (j'espère) ya rebbi bach matetnarvach
