### ISSUE TITLE
Client suppression

### ISSUE THREAD

**Issue by fcbrida** [charaf113/OneRakTa3ref#132]
impossible de supprimer un client !!! voila l'image 
![image](https://cloud.githubusercontent.com/assets/20947094/18811984/455cf296-82c4-11e6-86cc-137d2a0bd977.png)

**Comment by fcbrida** [comment]
je crois que c'est les clients qui ont deja une facture dans il faut faire les contraintes

**Comment by lotfiAliane** [comment]
c'est réglé
