### ISSUE TITLE
suppression Vente

### ISSUE THREAD

**Issue by fcbrida** [charaf113/OneRakTa3ref#136]
message affiche "Supprimer l'achat" alors qu'on est entrain de supprimer une vente

**Comment by fcbrida** [comment]
tout les boutons d'annuler sont a gauche et sur celui la il est a droite vaut mieux garder la meme chose partout

**Comment by fcbrida** [comment]
il faut aussi ajouter un message de confirmation après la suppression

**Comment by lotfiAliane** [comment]
c'est réglé
