### ISSUE TITLE
Modification Achat 

### ISSUE THREAD

**Issue by fcbrida** [charaf113/OneRakTa3ref#140]
1) les boutons + et - ne marche pas 
2) quand je change le nombre en écrivant une autre quantité le total ne change pas
3) quand je valide aucun message ne s'affiche 
4) quand je vérifie la facture que j'ai modifié tt est supprimé le total les articles tout.. alors que j'ai juste ajouté dans la quantité

**Comment by lotfiAliane** [comment]
réglé mais à vérifié bien vérifié
