### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by fcbrida** [charaf113/OneRakTa3ref#141]
1) Ali  il faut changer la taille et le rendre rectangle ! il faut aussi enlevé les bordures meme en format png il y a le vide hadek donc les bordure doive etre juste juste avec le logo pas plus
2) quand on clique sur le logo il affiche ça 
![image](https://cloud.githubusercontent.com/assets/20947094/18812306/27d38166-82d0-11e6-844e-38b2627c9664.png)

**Comment by lotfiAliane** [comment]
j'ai enlevé le logo le résultat est netement mieux
