### ISSUE TITLE
TVA vente

### ISSUE THREAD

**Issue by fcbrida** [charaf113/OneRakTa3ref#159]
la TVA se fait sur la facture uniquement et non pas sur les produits

**Comment by lotfiAliane** [comment]
?? ou ça dans le pdf ? ou dans la vue ?

**Comment by fcbrida** [comment]
dans les calcules

**Comment by lotfiAliane** [comment]
une capture

**Comment by lotfiAliane** [comment]
c'est pas un bug ni une érreure au contraire une info en + qui ne fais rien de mal on la garde
