### ISSUE TITLE
Erreur quand le type produit unique

### ISSUE THREAD

**Issue by ayoubensidhoum** [charaf113/OneRakTa3ref#51]
le nom doit d'être unique

**Comment by lotfiAliane** [comment]
Je crois que j'ai déja vérifier cette contrainte on peut pas ajouté deux type identique !

**Comment by ayoubensidhoum** [comment]
Oui mais le message d'erreur est moche : tu peux pas mettre un message ce type existe déja wela !!
![capture](https://cloud.githubusercontent.com/assets/20946708/17623413/cd44081a-6097-11e6-8fa5-71a2333891b4.JPG)

**Comment by lotfiAliane** [comment]
c'est réglé

**Comment by ayoubensidhoum** [comment]
Pas encore

**Comment by lotfiAliane** [comment]
réglé
