### ISSUE TITLE
Les tableaux

### ISSUE THREAD

**Issue by ayoubensidhoum** [charaf113/OneRakTa3ref#52]
Pour tt les tableaux il faut modifier les messages affichés en anglais !

*** Si le tableau est vide : No data available in table. faut mieux la rendre : Aucune donnée disponible.

*** Si la recherche donne aucun résultat : No matching records found. faut bien mettre : Aucun enregistrements correspondants trouvés.

*** Si la recherche donne aucun résultat : Showing 0 to 0 of 0 entries. faut la changé : Affichage 0 à 0 de 0 entrées.

**Comment by charaf113** [comment]
résolu
