### ISSUE TITLE
Erreur quand le libellé produit unique

### ISSUE THREAD

**Issue by ayoubensidhoum** [charaf113/OneRakTa3ref#53]
Changé message d'erreur

**Comment by lotfiAliane** [comment]
quel méssage ? merci de détaillé un plus s'il te plait quel fennetre et quel action , merci

**Comment by ayoubensidhoum** [comment]
Quand j'ajoute un type produit avec le même nom d'un type déjà ajouté : voilà le message d'erreur qui s'affiche (voir image) donc faut afficher un message : type déja existé 
![capture](https://cloud.githubusercontent.com/assets/20946708/17920746/24545ce2-69ce-11e6-9a74-eb64e8e9ee54.JPG)

**Comment by lotfiAliane** [comment]
la vérification de l'unicité du type_produit c'est ça ? normalement c'est fait
