### ISSUE TITLE
Ajouter facture achat code à bare

### ISSUE THREAD

**Issue by ayoubensidhoum** [charaf113/OneRakTa3ref#55]
quand je saisi un code à barre une fois j’appuie sur entrée le field code à barre sera vide

**Comment by charaf113** [comment]
c'est un bug ??!!

**Comment by ayoubensidhoum** [comment]
non désolé mais il faut que quand je saisi un code à barre une fois j’appuie sur entrée le field code à barre sera vide jm'excuse

**Comment by charaf113** [comment]
résolu
