### ISSUE TITLE
Ajouter facture achat

### ISSUE THREAD

**Issue by ayoubensidhoum** [charaf113/OneRakTa3ref#58]
faut ajouter fournisseur parce que fournisseur est spécifié pour un et un seul fournisseur

**Comment by charaf113** [comment]
je n'ai pas compris ?,

**Comment by ayoubensidhoum** [comment]
Il faut ajouter fournisseur 
Chaque facture d'achat est spécifié pour un seul fournisseur.
Comme Lotfi la fait pour vendre : il choisi le client pour une facture
