### ISSUE TITLE
Ajouter un nouveau produit code à barre 

### ISSUE THREAD

**Issue by ayoubensidhoum** [charaf113/OneRakTa3ref#60]
le code barre doit être unique

**Comment by lotfiAliane** [comment]
résoulu

**Comment by ayoubensidhoum** [comment]
il faut aussi changé le msg d'erreur quand le code-barre existe déja comme type produit : évité ce genre de message 
![capture](https://cloud.githubusercontent.com/assets/20946708/17920829/94b8b7c6-69ce-11e6-9097-bbc3ace0d430.JPG)

**Comment by lotfiAliane** [comment]
c'est réglé
