### ISSUE TITLE
Facture d'achat probleme ajout code à barre

### ISSUE THREAD

**Issue by ayoubensidhoum** [charaf113/OneRakTa3ref#63]
si j'ajoute un code à barre une ligne sa va être ajouté ok
mais j'ajoute le meme code à barre une autre ligne s'ajoutera alors que normalement quand la meme ligne du code barre déja ajouté la quantité +1

**Comment by charaf113** [comment]
c'est la meme chose ça ne posera aucun prob

**Comment by ayoubensidhoum** [comment]
oui je sais mais faut mieux le mettre dans la meme ligne coté interface
