### ISSUE TITLE
prix d'achat produit

### ISSUE THREAD

**Issue by ayoubensidhoum** [charaf113/OneRakTa3ref#71]
il faut ajouter prix d'achat d'un produit lors de l'ajout d'une facture d'achat : le prix d'achat d'un produit sera modifié a chaque insertion d'une facture d'achat et qui va prendre la dernière valeur

**Comment by charaf113** [comment]
Dans la conception de l'application on a choisit de modifier dans le produit et non pas dans l'achat puisque dans l'achat on utilise des produits déjà ajouté , alors si le prix d'achat change tu dois le modifier dans la section produit et la formule que doit appliquer lotfi c'est (l'ancien prix + le nouveau ) / 2

**Comment by lotfiAliane** [comment]
Je crois que s'il veux changer le prix d'un produit ça doit se faire au niveau de la gestion du produit

**Comment by lotfiAliane** [comment]
j'ai appliqué la formule
