### ISSUE TITLE
Facture d'achat prix Nan

### ISSUE THREAD

**Issue by ayoubensidhoum** [charaf113/OneRakTa3ref#72]
Si le field quantité est vide les prix Nan faut voir sa

**Comment by charaf113** [comment]
résolu

**Comment by ayoubensidhoum** [comment]
Pas encore

**Comment by charaf113** [comment]
Dans quel cas NAN s'affiche ?

**Comment by ayoubensidhoum** [comment]
![Uploading ici.png…]()

**Comment by ayoubensidhoum** [comment]
![ici](https://cloud.githubusercontent.com/assets/20946708/18815416/70dfde4c-8328-11e6-8e79-95f1e8e770e7.png)

**Comment by lotfiAliane** [comment]
il doit respecté un minimum des contrainte d'utilisation je vais la metre comme réglé meme si c'est pas le cas
